##服务器配置
server:
  port: 8080
  context-path:
  tomcat:
    uri-encoding: utf-8
    compression: on

##监控配置
management:
  context-path: /manager
  port: 8080
endpoints:
  shutdown:
    enabled: false




##注册中心配置
eureka:
  client:
    service-url:
#      defaultZone: http://192.168.10.201:8080/eureka/v2/
      defaultZone: http://localhost:32772/eureka/
  instance:
    preferIpAddress: true
    metadata-map:
      instanceId: ${spring.application.name}:${random.value}


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
#    username: root
#    password: mamahao
#
#custom:
#  datasource:
#    names: ds1,ds2
#    ds1:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
#      username: root
#      password: mamahao
#    ds2:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
#      username: root
#      password: mamahao

#数据源配置
datasource:
  xyz: 123
  groups:
    -
      group-name: ms0
      items:
        -
          name: ms0_ds0
          master: true
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
          username: root
          password: mamahao
        -
          name: ms0_ds1
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
          username: root
          password: mamahao
        -
          name: ms0_ds2
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
          username: root
          password: mamahao
    -
      group-name: ms1
      items:
        -
          name: ms1_ds0
          master: true
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
          username: root
          password: mamahao
        -
          name: ms1_ds1
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
          username: root
          password: mamahao
    -
      group-name: ms2
      items:
        -
          name: ms2_ds0
          master: true
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.1.6:3306/db_gd_dev?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true
          username: root
          password: mamahao

mybatis:
  config:
    mapper-locations: classpath*:mapper/*Mapper.xml
    type-aliases-package: com.mamahao.actsys.api.po
    base-package: com.mamahao.actsys.api.mapper
